import Link from "next/link";
import { BookOpen, Clock3, Layers } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { getCurrentTenantId } from "@/lib/auth";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { StatusBadge } from "@/components/status-badge";
import { EmptyState } from "@/components/empty-state";

// Reads live rows from Supabase on every request — never prerender this.
export const dynamic = "force-dynamic";

interface StoryRow {
  id: string;
  project_id: string | null;
  topic: string | null;
  logline: string | null;
  moral: string | null;
  duration_seconds: number | null;
  status: string | null;
  part_number: number | null;
  series_id: string | null;
  created_at: string | null;
}

function formatDuration(seconds: number | null) {
  if (seconds === null || Number.isNaN(seconds)) return "—";
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const rest = seconds % 60;
  return rest === 0 ? `${minutes}m` : `${minutes}m ${rest}s`;
}

function formatDate(value: string | null) {
  if (!value) return "—";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "—";
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export default async function StoriesPage() {
  const supabase = await createClient();
  const tenantId = (await getCurrentTenantId()) ?? "";

  let stories: StoryRow[] = [];
  let errored = false;
  try {
    const { data, error } = await supabase
      .from("stories")
      .select(
        "id, project_id, topic, logline, moral, duration_seconds, status, part_number, series_id, created_at"
      )
      .eq("tenant_id", tenantId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    stories = data ?? [];
  } catch {
    errored = true;
  }

  const total = stories.length;
  const durations = stories
    .map((s) => s.duration_seconds)
    .filter((d): d is number => typeof d === "number");
  const avgDuration =
    durations.length > 0
      ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length)
      : null;
  const seriesCount = new Set(
    stories.map((s) => s.series_id).filter(Boolean)
  ).size;

  return (
    <div>
      <PageHeader
        title="Story Queue"
        description="Track stories moving through ideation and scripting."
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <StatCard
          label="Total stories"
          value={errored ? 0 : total}
          icon={BookOpen}
          error={errored}
        />
        <StatCard
          label="Avg. duration"
          value={errored ? 0 : formatDuration(avgDuration)}
          icon={Clock3}
          error={errored}
        />
        <StatCard
          label="Series in progress"
          value={errored ? 0 : seriesCount}
          icon={Layers}
          error={errored}
        />
      </div>

      <div className="mt-8">
        {errored ? (
          <EmptyState
            icon={BookOpen}
            title="Couldn't load stories"
            description="There was a problem reaching the stories table. Check your Supabase connection."
          />
        ) : stories.length === 0 ? (
          <EmptyState
            icon={BookOpen}
            title="No stories yet"
            description="Stories generated by the pipeline will show up here."
          />
        ) : (
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            {stories.map((story) => (
              <Link
                key={story.id}
                href={`/stories/${story.id}`}
                className="group flex flex-col gap-3 rounded-xl border border-border bg-elevated p-5 shadow-sm transition-[transform,box-shadow] duration-200 ease-out hover:-translate-y-0.5 hover:shadow-lg hover:shadow-black/5 dark:hover:shadow-black/30"
              >
                <div className="flex items-start justify-between gap-3">
                  <h2
                    lang="hi"
                    className="text-lg font-semibold leading-snug text-foreground"
                  >
                    {story.topic || "Untitled story"}
                  </h2>
                  <StatusBadge
                    status={story.status ?? "pending"}
                    className="shrink-0"
                  />
                </div>

                {story.moral ? (
                  <p
                    lang="hi"
                    className="line-clamp-2 text-sm text-muted-foreground"
                  >
                    {story.moral}
                  </p>
                ) : null}

                <div className="mt-auto flex flex-wrap items-center gap-x-4 gap-y-1.5 pt-2 text-xs text-muted-foreground">
                  <span className="tabular-nums">
                    {formatDuration(story.duration_seconds)}
                  </span>
                  {story.part_number ? (
                    <span>Part {story.part_number}</span>
                  ) : null}
                  <span className="tabular-nums">
                    {formatDate(story.created_at)}
                  </span>
                </div>
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
