import { UploadCloud } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { EmptyState } from "@/components/empty-state";

// Reads live rows from Supabase on every request — never prerender this.
export const dynamic = "force-dynamic";

interface VideoRow {
  id: string;
  topic: string | null;
  status: string | null;
  aspect_ratio: string | null;
  created_at: string | null;
}

function formatDate(value: string | null) {
  if (!value) return "—";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "—";
  return date.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export default async function UploadsPage() {
  const supabase = createAdminClient();

  let videos: VideoRow[] = [];
  let errored = false;

  try {
    const { data, error } = await supabase
      .from("videos")
      .select("id, topic, status, aspect_ratio, created_at")
      .order("created_at", { ascending: false });
    if (error) throw error;
    videos = data ?? [];
  } catch {
    errored = true;
  }

  return (
    <div>
      <PageHeader
        title="Uploads"
        description="Upload history for videos generated by the pipeline."
      />

      {errored ? (
        <EmptyState
          icon={UploadCloud}
          title="Couldn't load uploads"
          description="There was a problem reaching the videos table. Check your Supabase connection."
        />
      ) : videos.length === 0 ? (
        <EmptyState
          icon={UploadCloud}
          title="No uploads yet"
          description="Videos that finish the pipeline will show up here with their upload status."
        />
      ) : (
        <div className="rounded-xl border border-border bg-elevated">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground">
                  <th className="px-5 py-3 font-medium">Topic</th>
                  <th className="px-5 py-3 font-medium">Status</th>
                  <th className="px-5 py-3 font-medium">Aspect ratio</th>
                  <th className="px-5 py-3 font-medium">Created</th>
                </tr>
              </thead>
              <tbody>
                {videos.map((video) => (
                  <tr key={video.id} className="border-b border-border/60 last:border-0">
                    <td className="px-5 py-3 font-medium text-foreground">
                      {video.topic || "Untitled video"}
                    </td>
                    <td className="px-5 py-3">
                      <StatusBadge status={video.status ?? "planned"} />
                    </td>
                    <td className="px-5 py-3 tabular-nums text-muted-foreground">
                      {video.aspect_ratio ?? "—"}
                    </td>
                    <td className="px-5 py-3 tabular-nums text-muted-foreground">
                      {formatDate(video.created_at)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
